### ISSUE TITLE
Sample code not play video

### ISSUE THREAD

**Issue by swatiPuri26** [Axinom/drm-quick-start-ios#1]
I am trying to play video but it display following screen.

![image](https://user-images.githubusercontent.com/39939425/40957091-22c5604a-68b1-11e8-8ade-98b9f0a5078f.png)

**Comment by Heronyme** [comment]
Hello!

Sorry for such a long delay. Seems that this issue was forgotten.

Closing it for now, as a long time has passed. But feel free to reopen if you still have questions.

Please note that this iOS FPS app is only intended to be used for integration purposes with Axinom DRM. Before using it, make sure you have set up an Axinom DRM demo account. Registration can be performed here: https://drm.axinom.com/evaluation-account/.
